version: '3'
services:
  # ///////////////////////////  Others  ///////////////////////////
  500h-sar-mariaDB:
    container_name: ${MYSQL_HOST}
    image: mariadb
    restart: always
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    networks:
      - 500Historias_SAR
  500h-sar-rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: ${RABBITMQ_HOST}
    hostname: 500h-sar-rabbitmq
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '15672:15672'
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER = ${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS = ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
      - ./conf/myrabbit.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - 500Historias_SAR
  500h-sar-redis:
    container_name: ${REDIS_HOST}
    restart: on-failure
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    env_file:
      - .env
    volumes:
      - ./redis/data:/data
    networks:
      - 500Historias_SAR

  # ///////////////////////////  APIs  ///////////////////////////
  500h-sar-api:
    container_name: 500h-sar-api
    restart: on-failure
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
      target: development
    command: npm run start:dev api
    env_file:
      - .env
    depends_on:
      - 500h-sar-rabbitmq
      - 500h-sar-mariaDB
      - 500h-sar-auth
      - 500h-sar-challenges
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    networks:
      - 500Historias_SAR
  500h-sar-auth:
    container_name: 500h-sar-auth
    restart: on-failure
    build:
      context: .
      dockerfile: ./src/auth/Dockerfile
      target: development
    command: npm run start:dev auth # overrides CMD from dockerfile
    depends_on:
      - 500h-sar-rabbitmq
      - 500h-sar-mariaDB
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    networks:
      - 500Historias_SAR
  500h-sar-challenges:
    container_name: 500h-sar-challenges
    restart: on-failure
    build:
      context: .
      dockerfile: ./src/challenges/Dockerfile
      target: development
    command: npm run start:dev challenges # overrides CMD from dockerfile
    env_file:
      - .env
    depends_on:
      - 500h-sar-rabbitmq
      - 500h-sar-mariaDB
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    networks:
      - 500Historias_SAR
volumes:
  redis:
    driver: local
  rabbitmq:
networks:
  500Historias_SAR:
    driver: bridge
